name: Compile LaTeX Resume

on:
  push:
    branches: [ main ]
    paths: [ '**.tex' ]  # Only run when .tex files are modified
  pull_request:
    branches: [ main ]
    paths: [ '**.tex' ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  compile-latex:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install LaTeX with XeTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

    - name: Compile LaTeX to PDF with XeLaTeX
      run: |
        # Find all .tex files and compile them using xelatex
        for tex_file in *.tex; do
          if [ -f "$tex_file" ]; then
            echo "Compiling $tex_file with XeLaTeX..."
            xelatex -interaction=nonstopmode "$tex_file"
            # Run twice to resolve references
            xelatex -interaction=nonstopmode "$tex_file"
            echo "Successfully compiled $tex_file to ${tex_file%.tex}.pdf"
          fi
        done
        
    - name: Check if PDF was generated
      run: |
        if ls *.pdf 1> /dev/null 2>&1; then
          echo "PDF files generated successfully:"
          ls -la *.pdf
        else
          echo "No PDF files found!"
          exit 1
        fi
        
    - name: Commit and push PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add all generated PDF files
        git add *.pdf
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-compile: Update resume PDF [skip ci]"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: '*.pdf'
        retention-days: 30
